name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # every 6 hours (UTC). Change this if you want.
    - cron: '0 */6 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci

      # Run your scraper to refresh events.json
      - name: Scrape & build events.json
        env:
          # Set to "0" if you want Welly included in the auto runs
          SKIP_WELLY: "0"
        run: |
          mkdir -p public
          node ./scrape-hull-venues.js > public/events.json || echo "scrape failed, keeping previous"

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
